baseURL = "https://example.com/"
languageCode = "es"
title = "Mi Blog Técnico"
theme = "blowfish"


enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

minify = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"



[params]
  # Color scheme
  colorScheme = "auto" # "dark" or "light" or "auto"
  # Enable search
  enableSearch = true
  # Enable code copy button
  enableCodeCopy = true
  # Enable RSS
  enableRSS = true
  # Enable social icons
  enableSocial = true
  # Author
  author = "Marco"
  # Description
  description = "Un blog sobre tecnología, programación y más."
  # Keywords
  keywords = ["blog", "tecnologia", "programacion"]

  # Main sections
  mainSections = ["posts"]

  # Social links
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/marcosba" # Replace with your GitHub URL
  # [[params.social]]
  #   name = "Twitter"
  #   icon = "twitter"
  #   url = "https://twitter.com/your_twitter_handle"

  # Footer
  [params.footer]
    showPoweredBy = true
    showThemeAttribution = true
    showCopyright = true
    showSocial = true
    showNewContent = true
    showBackToTop = true
    showFooterLinks = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # is necessary for search

