baseURL = "https://example.com/"
languageCode = "es"
title = "Mi Blog Técnico"
theme = "blowfish"


enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

minify = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"



[params]
  # Color scheme
  colorScheme = "auto" # "dark" or "light" or "auto"
  # Enable search
  enableSearch = true
  # Enable code copy button
  enableCodeCopy = true
  # Enable RSS
  enableRSS = true
  # Enable social icons
  enableSocial = true
  # Author
  [params.author]
    name = "Marco"
  # Description
  description = "Un blog sobre tecnología, programación y más."
  # Keywords
  keywords = ["blog", "tecnologia", "programacion"]
  defaultFeaturedImage = ""
  defaultBackgroundImage = ""

  # Main sections
  mainSections = ["posts"]

  

[outputs]
  home = ["HTML", "RSS", "JSON"] # is necessary for search

