[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.129.0"
  HUGO_ENV = "production"
  # HUGO_ENABLEGITINFO = "true" # Descomenta si quieres usar informaci√≥n de Git en Hugo

[context.deploy-preview.environment]
  HUGO_VERSION = "0.129.0"
  HUGO_ENV = "production"
  # HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.129.0"
  HUGO_ENV = "production"
  # HUGO_ENABLEGITINFO = "true"
